name: Deploy to Amazon ECR

on: 
  push:
    branches: [ main ]  # Ensure this matches your branch name

jobs:
  build:
    name: Build and Push Image to Amazon ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag the Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/webapp-repo:latest -f Dockerfile .
          docker tag ${{ steps.login-ecr.outputs.registry }}/webapp-repo:latest ${{ steps.login-ecr.outputs.registry }}/webapp-repo:latest

      - name: Push image to Amazon ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/webapp-repo:latest

